[package]
name = "reqwest-eventsource"
version = "0.6.0"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"
resolver = "2"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/jpopesculian/reqwest-eventsource"
documentation = "https://docs.rs/reqwest-eventsource/"
repository = "https://github.com/jpopesculian/reqwest-eventsource"
description = "Helper to build an Eventsource using reqwest"
keywords = ["sse", "eventsource", "reqwest", "stream", "event"]
categories = ["web-programming::http-client", "no-std", "parsing", "asynchronous"]

[features]
middleware = ["dep:reqwest-middleware"]

[[example]]
name = "simple_digest"
path = "examples/simple_digest.rs"
required-features = ["middleware"]

[dependencies]
eventsource-stream = "0.2.3"
reqwest = { version = "0.12.0", default-features = false, features = ["stream"] }
futures-core = "0.3.5"
pin-project-lite = "0.2.8"
nom = "7.1.0"
mime = "0.3.16"
futures-timer = "3.0.2"
thiserror = "1.0.30"
reqwest-middleware = { version = "0.4.2", optional = true }

[dev-dependencies]
futures = "0.3.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures-retry = "0.6"
pin-utils = "0.1"
rocket = "0.5.0"
digest_auth = "0.3.1"
async-trait = "0.1.89"
http = "1.3.1"

